### ISSUE TITLE
Create example that demonstrates asynchronous JavaScript

### ISSUE THREAD

**Issue by catarak** [Cycling74/n4m-examples#10]

**Comment by julianrubisch** [comment]
Can I help?

**Comment by catarak** [comment]
yeah! we're working on rearranging the examples, and I think this one should go in the [core examples repo](https://github.com/cycling74/n4m-core-examples). i'll move this issue over there, so hold tight for now.

**Comment by fde31** [comment]
Closing out in favour of core-examples
