### ISSUE TITLE
Add blurb about using a uniquely-named feature branch for PR's

### ISSUE THREAD

**Issue by starakaj** [Cycling74/n4m-examples#14]

**Comment by starakaj** [comment]
See also the very helpful https://github.com/processing/p5.js-web-editor/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by julianrubisch** [comment]
You could also supply a PR template

**Comment by catarak** [comment]
it will probably make sense to move this ticket to the [community examples repo](https://github.com/cycling74/n4m-community).
