### ISSUE TITLE
bug in routeServer example : dict is not recognized

### ISSUE THREAD

**Issue by vincentgoudard** [Cycling74/n4m-examples#18]
#### Nature of issue?

- [x] Found a bug in an example
- [ ] Existing example enhancement
- [ ] Suggest a new example

#### Details about the bug: 

- Max version:  Max8.0.2 beta f93ff5f
- Operating System: OSX Sierra
- Name of example: routeServer
- Steps to reproduce this:

When I load the browser URL, node.script receives the request, but the dict send in return is not accepted/parsed correctly by the node script. Max console says :

```
tonode: dictionary u211002778
tonode: uuid: 5969d170-f18d-11e8-ab5d-f5099fed51c4
htmlTitle: "Welcome to Max Node"
htmlContent: "<h1>Welcome to Max Node!</h1> <p> There's a lot to see here - let's check out some options: </p> <p> <a href=/getData?test1=gravy&test2=boat>Get some data</a><br /> <a href=/getHTML>Get some HTML</a><br /> </p>"
stdout: invalid message - only dictionaries accepted as messages
stdout: [0mGET / [31m500 [0m2002.989 ms - -[0m
stdout: [0mGET /favicon.ico [36m304 [0m0.483 ms - -[0m

```

**Comment by catarak** [comment]
thanks for reporting!

**Comment by fde31** [comment]
@vincentgoudard I cannot reproduce on my end. Is this still an issue for you? @catarak were u able to reproduce?

**Comment by vincentgoudard** [comment]
@fde31  Just tried it with latest Max (8.0.4) and after fetching [C74/n4m](https://github.com/Cycling74/n4m-examples) and it works fine now.
