### ISSUE TITLE
error: "No Value For Key..." in .env file

### ISSUE THREAD

**Issue by billythemusical** [Cycling74/n4m-examples#31]
#### Nature of issue?

- [x] Found a bug in an example

#### Details about the bug: 

- Max version: Max 8.0.5 (64-bit Mac)
- Operating System: Mac OS Sierra 10.12.6
- Name of example: freesound-search.maxpat, freesound-sequencer.maxpat
- Steps to reproduce this: I opened ".env-template" with Text Edit and Saved As... ".env".  I copied and pasted each corresponding key and pasted them directly after the "=" sign with no additions.  I saved the file.  I then opened the "freesound-search" example in Max and clicked the "script npm install" message and the console indicated that the install had completed.  Then when I clicked the "script start" button, I got the following errors:
 
> node.script: No value for key FREESOUND_CLIENT_KEY in .env file. Please make sure to create a file called .env with a Freesound API Client key.
node.script: No value for key FREESOUND_CLIENT_SECRET in .env file. Please make sure to create a file called .env with a Freesound API Client Secret.

So, this should not be the case since I replaced the ".env-template" values with the values from the FreeSound API and saved the file as ".env".  

Please advise :)

Best,
Billy

**Comment by catarak** [comment]
thanks for reporting, billy! i am unfortunately not able to reproduce. can you make sure that you saved the `.env` file in the folder `n4m-examples/freesound`? if that still doesn't work, maybe you can try emailing me your `.env` file (to cassie at cycling74.com) so i can see if it is formatted correctly.

**Comment by billythemusical** [comment]
hey cassie!  thanks for getting back to me.  I just drafted an email to you and when I attached the .env file and it showed up as ".env.txt" ...  So I got info on the file and removed the .txt from the file name and voila!  The patch works as advertised :)

**Comment by catarak** [comment]
aha! a hidden extension ✨a suggestion for how to avoid that scenario again is to use a text editor that's optimized for use with programming, such as Sublime Text, Atom, or Visual Studio Code, which won't hide files that begin with a `.` and won't hide extensions.

**Comment by paolopastorino** [comment]
Hey guys!
I have the same problem but I can't solve it. 
Could you help me, please?

**Comment by paolopastorino** [comment]
Sorry, problem solved.
