### ISSUE TITLE
sockets and timeouts

### ISSUE THREAD

**Issue by danieljamesross** [Cycling74/n4m-examples#33]
- Max version: 8.1.2
- Operating System: **MacOSX**
- Name of example: **Sockets**
- Steps to reproduce this: **I can connect multiple devices to the websocket, but when one falls asleep, it disrupts the connect for all the others. How do I handle multiple devices connected to the same websocket server?**

**Comment by fde31** [comment]
Hi there,

sorry for the slight delay on this. Can you be a bit more specific on how to exactly reproduce this?

Thanks

**Comment by danieljamesross** [comment]
Hi Florian,

Don't worry. I think it might be a websocket problem not logging multiple connections rather than one with the patch. I've been rebuilding with socket.io and not noticing the same error.

Cheers,
Dan
