### ISSUE TITLE
Stream real-time audio from Max to a web

### ISSUE THREAD

**Issue by Dazzid** [Cycling74/n4m-examples#34]
[example suggestion] I have a quick question, is it possible to stream audio from a Max patch to be heard using a web-server, like an online radio station?

**Comment by starakaj** [comment]
This is definitely possible, but not something that you'd use Node for Max for. You'll need a platform to host your stream, streaming software to reach that platform, and some way to get audio from Max to that streaming software. So on Mac for example you could use Soundflower to move audio into OBS, and then stream from OBS to a platform like Mixcloud. I hope that helps!
