### ISSUE TITLE
freesound sample broken (api change?)

### ISSUE THREAD

**Issue by muccio** [Cycling74/n4m-examples#36]
#### Nature of issue?

- [x] Found a bug in an example
- [ ] Existing example enhancement
- [ ] Suggest a new example

#### Details about the bug: 

- Max version: 
- Operating System: 
- Name of example: 
- Steps to reproduce this:

**Comment by dennisrcao** [comment]
Same with me, freesound-search and freesound-sequencer are not working for me
I forked the repo, applied for an API key, created a .env and copied in client ID and client secret/API key
 opened up freesound-search and ran npm install then ran the script, nothing shows up in the search section after running a search.

**Comment by dennisrcao** [comment]
Just ran a GET request by typing into my browser: 
https://freesound.org/apiv2/search/text/?query=piano&token= ________ <--- inserted my freesound API key here 

and it returned valid JSON list of piano sounds, so we can eliminate the API being down as an issue.

**Comment by b40t** [comment]
Same problem here, when I run a search through the example patch I only get a blank node.script: message in the console. No real error, but no search results either.
