### ISSUE TITLE
Node for Max - can't get node process manager to run

### ISSUE THREAD

**Issue by s4ik** [Cycling74/n4m-examples#37]
- [x] Found a bug in an example
- Max version: Max 8.1.0
- Operating System: Mac OS 12.1 Monterey
- Problem : 

I'm trying to get Max to communicate with a web server using Node.js, but I can't get the script running. I know I can only run the script from Max for it to find 'max-api', and I've tried with several examples, but it won't work.

Each time I press 'script npm install' or 'script start' it will log 'node process manager not running'. If I press 'script reboot' it will try to start it 5 times and say 'Node for Max process manager quit after 5 restarts'.

I can't find anyone with the same problem, and i really don't know how to solve it. I hope someone will be able to help !

Thanks already.

- Steps to reproduce this:
It can be reproduced using the basic example Node Patch 'node.script.maxhelp'.

- Error log in the console : See screenshot

![image](https://user-images.githubusercontent.com/82897120/151936351-e29d5749-e0b6-462f-be14-064e93185612.png)

Thank you !

**Comment by fde31** [comment]
Hi there.
This seems to be a case that's more suitable for the Cycling '74 Support. They will be able to work with you in finding out what the exact issue might be and resolving it. From first sight the message `Process Manager not running` hints at something that goes wrong even before you attempt to start the script via the messages.

Would you mind reaching out to support via https://cycling74.com/support/contact ?

Thanks!
