### ISSUE TITLE
Example suggestion

### ISSUE THREAD

**Issue by Gelbox** [Cycling74/n4m-examples#40]
#### New example details:

I have been experimenting with Node, and I'd like to see an example of calling GraphQL APIs from an existing server that uses API key authorisation. It would also be good to know how to parse and show the data the server returns.

Thank you!

**Comment by fde31** [comment]
Hi @Gelbox and thanks for your request. My first reaction is that this seems less of a "Max specific" example / request and the documentation of some common Node packages to deal with GraphQL APIs might be better suited and help you.

If you are looking for a package with some example to get started, I'd recommend the `graphql-request` package - https://github.com/jasonkuhrt/graphql-request
