### ISSUE TITLE
file-upload example: file name/location is not routed correctly out of node.script object in max patch

### ISSUE THREAD

**Issue by tmarasco125** [Cycling74/n4m-examples#5]
In the File-Upload example, the instructions state that once an audio file is uploaded on the server page, it will be played in the 'file-upload' max patch. This does not happen, as there is a missing "prepend open" object missing that should point sfplay~ to the _filesin directory location. The t s b object also doesn't trigger the opened file after turning the dac on.

**Comment by starakaj** [comment]
Should be fixed, thanks for reporting!
