### ISSUE TITLE
Extend Linting / CI Integration

### ISSUE THREAD

**Issue by fde31** [Cycling74/n4m-examples#8]
Currently there is a linting file but no CI driven, automated linting/testing happening.

**Comment by fde31** [comment]
once @benbrackenc74 has published the following to npm https://github.com/Cycling74/eslint-config-c74 it should be relatively easy to base all linting on these rules etc.

**Comment by catarak** [comment]
My vote is to use Travis CI! It's already set up for use with the @Cycling74 Organization.

**Comment by catarak** [comment]
this is done and [on travis](https://travis-ci.org/Cycling74/n4m-examples)!
